version: '3'
services:
  zabbix-agent:
    image: zabbix/zabbix-agent
    container_name: zabbix-agent
    ports:
      - 10050:10050
    environment:
      - ZBX_HOSTNAMEITEM=system.hostname
      - ZBX_SERVER_HOST=192.168.0.108